applications:
  app:
    source:
      root: "/"
    type: "nodejs:22"
    web:
      locations:
        "/":
          root: "public"
          index:
            - "index.html"
            - "README.md"
          scripts: false
          allow: true

routes:
  "https://{default}/": 
    type: upstream
    upstream: "app:http"