applications:
  app:
    source:
      root: /
    type: php:8.4
    build:
      flavor: composer
    # Installs global dependencies as part of the build process. They're independent of your app's dependencies and
    # are available in the PATH during the build process and in the runtime environment. They're installed before
    # the build hook runs using a package manager for the language.
    # More information: https://docs.upsun.com/create-apps/app-reference/single-runtime-image.html#dependencies
    dependencies:
      nodejs:
        n: "*"
        npx: "*"
        yarn: "^1.22.0"
      php:
        composer/composer: "^2"

    web:
      locations:
        "/":
          root: "web"
          passthru: "/index.php"
          index:
            - index.php
        "/sites/default/files":
          root: "web/sites/default/files"
          scripts: false
          allow: true
    mounts:
      "/web/sites/default/files": "shared:files/files"
      "/tmp": "shared:files/tmp"
      "/private": "shared:files/private"
    relationships:
      database: "mariadb:mysql"
    hooks:
      build: |
        set -eux
        composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader --no-dev
        n auto || n lts
        hash -r
        yarn

      deploy: |
        set -e
        cd web
        /vendor/bin/drush -y cache-rebuild
        /vendor/bin/drush -y updatedb
        /vendor/bin/drush -y config-import

services:
  mariadb:
    type: mariadb:10.11

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
