applications:
  app:
    source:
      root: /
    type: php:8.3
    build:
      flavor: composer
    web:
      locations:
        "/":
          root: "web"
          passthru: "/index.php"
          index:
            - index.php
        "/sites/default/files":
          root: "web/sites/default/files"
          scripts: false
          allow: true
    mounts:
      "/web/sites/default/files": "shared:files/files"
      "/tmp": "shared:files/tmp"
      "/private": "shared:files/private"
    relationships:
      database: "mariadb:mysql"
    hooks:
      build: |
        set -e
        composer install --no-dev --optimize-autoloader
      deploy: |
        set -e
        cd web
        drush -y cache-rebuild
        drush -y updatedb
        drush -y config-import

services:
  mariadb:
    type: mariadb:10.11

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"