applications:
  app:
    source:
      root: "/"
    type: "nodejs:22"
    hooks:
      build: |
        # Install pandoc using GitHub releases
        curl -fsS https://raw.githubusercontent.com/upsun/snippets/main/src/install-github-asset.sh | bash /dev/stdin "jgm/pandoc" "3.5" "pandoc-3.5-linux-amd64.tar.gz"
        
        # Create public directory if it doesn't exist
        mkdir -p public
        
        # Convert README.md to HTML using pandoc
        /app/.global/bin/pandoc README.md -o public/index.html --standalone --title "Upsun Add-on Test Project"
    web:
      locations:
        "/":
          root: "public"
          index:
            - "index.html"
          scripts: false
          allow: true

routes:
  "https://{default}/": 
    type: upstream
    upstream: "app:http"