applications:
  drupal:
    source:
      root: /
    type: php:8.4
    build:
      flavor: composer
    # Installs global dependencies as part of the build process. They're independent of your app's dependencies and
    # are available in the PATH during the build process and in the runtime environment. They're installed before
    # the build hook runs using a package manager for the language.
    # More information: https://docs.upsun.com/create-apps/app-reference/single-runtime-image.html#dependencies
    dependencies:
      nodejs:
        n: "*"
        npx: "*"
        yarn: "^1.22.0"
      php:
        composer/composer: "^2"

    web:
      locations:
        "/":
          root: "web"
          passthru: "/index.php"
          index:
            - index.php
        "/sites/default/files":
          root: "web/sites/default/files"
          scripts: false
          allow: true
    variables:
      env:
        N_PREFIX: "/app/.global"

    mounts:
      "/web/sites/default/files": "shared:files/files"
      "/tmp": "shared:files/tmp"
      "/private": "shared:files/private"
    relationships:
      database: "mariadb:mysql"
    hooks:
      build: |
        set -eux

      deploy: |
        set -e
        php ./drush/upsun_generate_drush_yml.php
        cd web
        bash $PLATFORM_APP_DIR/drush/upsun_deploy_drupal.sh


services:
  mariadb:
    type: mariadb:10.11

routes:
  "https://{default}/":
    type: upstream
    upstream: "drupal:http"
